"""
═══════════════════════════════════════════════════════════════
SESSION MODELS — Chat Session Context Preservation
═══════════════════════════════════════════════════════════════
Models for tracking the full conversational context across
all stages: initial Q1-Q3, dynamic persona questions, and
tool recommendations.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class SessionStage(str, Enum):
    """Current stage of the user's session flow."""
    OUTCOME = "outcome"           # Q1: Growth bucket selection
    DOMAIN = "domain"             # Q2: Sub-category / domain selection
    TASK = "task"                 # Q3: Task selection
    DYNAMIC_QUESTIONS = "dynamic_questions"  # AI-generated follow-up questions
    RECOMMENDATION = "recommendation"       # Final tool recommendation
    COMPLETE = "complete"


class QuestionAnswer(BaseModel):
    """A single question-answer pair."""
    question: str
    answer: str
    question_type: str = "static"  # "static" for Q1-Q3, "dynamic" for AI-generated


class SessionContext(BaseModel):
    """
    Full session context preserved across the chat flow.
    Tracks every Q&A, persona loaded, and recommendations given.
    """
    session_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Current stage
    stage: SessionStage = SessionStage.OUTCOME

    # Q1: Outcome / Growth Bucket
    outcome: Optional[str] = None
    outcome_label: Optional[str] = None

    # Q2: Domain / Sub-Category
    domain: Optional[str] = None

    # Q3: Task
    task: Optional[str] = None

    # Persona doc loaded for this domain
    persona_doc_name: Optional[str] = None
    persona_context_loaded: bool = False

    # All Q&A pairs (static + dynamic)
    questions_answers: list[QuestionAnswer] = []

    # Dynamic questions generated by the AI agent
    dynamic_questions: list[str] = []
    dynamic_questions_asked: int = 0
    dynamic_questions_total: int = 0

    # Recommended tools
    recommended_extensions: list[dict[str, Any]] = []
    recommended_gpts: list[dict[str, Any]] = []
    recommended_companies: list[dict[str, Any]] = []

    # Free-form conversation history for the AI agent
    agent_conversation: list[dict[str, str]] = []


# ── API Request/Response Models ────────────────────────────────


class GenerateDynamicQuestionsRequest(BaseModel):
    """Request to generate dynamic follow-up questions after Q1-Q3."""
    session_id: str
    outcome: str
    outcome_label: str
    domain: str
    task: str


class DynamicQuestion(BaseModel):
    """A question with options — loaded directly from persona documents."""
    question: str
    options: list[str] = []
    allows_free_text: bool = True
    section: str = ""         # problems, rca_bridge, opportunities
    section_label: str = ""   # Human-readable label


class GenerateDynamicQuestionsResponse(BaseModel):
    """Response containing AI-generated dynamic questions."""
    session_id: str
    questions: list[DynamicQuestion]
    persona_loaded: str


class SubmitDynamicAnswerRequest(BaseModel):
    """Request to submit an answer to a dynamic question."""
    session_id: str
    question_index: int
    answer: str


class SubmitDynamicAnswerResponse(BaseModel):
    """Response after submitting a dynamic answer."""
    session_id: str
    next_question: Optional[DynamicQuestion] = None
    all_answered: bool = False


class GetRecommendationsRequest(BaseModel):
    """Request to get final tool recommendations based on all answers."""
    session_id: str


class ToolRecommendation(BaseModel):
    """A single tool recommendation."""
    name: str
    description: str
    url: Optional[str] = None
    category: str  # 'extension', 'gpt', 'company'
    free: Optional[bool] = None
    rating: Optional[str] = None
    why_recommended: str = ""


class GetRecommendationsResponse(BaseModel):
    """Final recommendations response with full session context."""
    session_id: str
    extensions: list[ToolRecommendation] = []
    gpts: list[ToolRecommendation] = []
    companies: list[ToolRecommendation] = []
    summary: str = ""
    session_context: dict[str, Any] = {}
